//go:build full

package interp_test

// Sprint: #243; Story: #675; Story-ID: 6ee00d8029b3
//
// cmd/go's generated test main under the interpreter: MainStart RETAINS its
// four descriptor slices in the *M it returns, so the bridge may not hand it
// a copy. Under the backend-asserted test-main fact the program-package
// bindings are transferred exclusively (bashpp_native_transfer.go): the
// dependency's decoded slice is the storage of record, the bindings are
// rebound to it, and M.Run then owns the scheduler exactly as testing.Main
// does. The native oracle cannot run these programs (only cmd/go may import
// testing/internal/testdeps), so the expectations are what Go's own test
// binary prints for the same driver.

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"mvdan.cc/sh/v3/gosource"
	"mvdan.cc/sh/v3/interp"
	"mvdan.cc/sh/v3/syntax"
)

const s243TestMainIdentity = "example.com/app.test"

// runGoSourceTestMain runs one source as cmd/go's generated test main: the
// fact is asserted to the front end (Options.TestMain) and to the runner
// (GoSourceIdentity), exactly as bashy --go-test-main passes it through.
func runGoSourceTestMain(t *testing.T, source string, testMain bool) (goSourceOutcome, error) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "_testmain.go")
	if err := os.WriteFile(path, []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	program, err := gosource.Parse(strings.NewReader(source), path, gosource.Options{RunMain: true, ImportPath: s243TestMainIdentity, TestMain: testMain})
	if err != nil {
		return goSourceOutcome{}, err
	}
	var stdout, stderr bytes.Buffer
	runner, err := interp.New(interp.Lang(syntax.LangBashPP), interp.Dir(dir), interp.StdIO(nil, &stdout, &stderr), interp.GoSourceIdentity(s243TestMainIdentity, testMain))
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
	defer cancel()
	err = runner.Run(ctx, program.File)
	outcome := goSourceOutcome{stdout: stdout.String(), stderr: stderr.String()}
	var status interp.ExitStatus
	if errors.As(err, &status) {
		outcome.status = int(status)
		err = nil
	}
	if leftovers, _ := filepath.Glob(filepath.Join(dir, ".bashpp*")); len(leftovers) > 0 {
		t.Fatalf("bridge workspace leaked: %v", leftovers)
	}
	return outcome, err
}

// The driver exactly as cmd/go's testmainTmpl spells it for two tests and no
// benchmarks, fuzz targets or examples, with the test bodies in the program
// package so the whole program is one source.
const s243GeneratedDriver = `// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"testing"
	"testing/internal/testdeps"
)

func TestAlpha(t *testing.T) {
	fmt.Println("alpha ran")
	if 1+1 != 2 {
		t.Errorf("arithmetic")
	}
}

func TestBeta(t *testing.T) {
	fmt.Println("beta ran")
}

var tests = []testing.InternalTest{
	{"TestAlpha", TestAlpha},
	{"TestBeta", TestBeta},
}

var benchmarks = []testing.InternalBenchmark{
}

var fuzzTargets = []testing.InternalFuzzTarget{
}

var examples = []testing.InternalExample{
}

func init() {
	testdeps.ModulePath = "example.com/app"
	testdeps.ImportPath = "example.com/app"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)
	os.Exit(m.Run())
}
`

func TestGoSourceS243GeneratedTestMainTransfersDescriptors(t *testing.T) {
	got, err := runGoSourceTestMain(t, s243GeneratedDriver, true)
	if err != nil {
		t.Fatalf("Runner: %v; stderr: %s", err, got.stderr)
	}
	want := goSourceOutcome{stdout: "alpha ran\nbeta ran\nPASS\n"}
	if got != want {
		t.Fatalf("Runner %+v; want %+v", got, want)
	}
}

// A failing test body is reported by the real scheduler through the retained
// descriptor — the interpreter ran the body, testing decided the outcome —
// and the driver exits with M.Run's code.
func TestGoSourceS243GeneratedTestMainReportsFailure(t *testing.T) {
	source := strings.Replace(s243GeneratedDriver, "if 1+1 != 2 {", "if 1+1 == 2 {", 1)
	got, err := runGoSourceTestMain(t, source, true)
	if err != nil {
		t.Fatalf("Runner: %v; stderr: %s", err, got.stderr)
	}
	if got.status != 1 || !strings.HasPrefix(got.stdout, "alpha ran\n") || !strings.Contains(got.stdout, "--- FAIL: TestAlpha") || !strings.Contains(got.stdout, "arithmetic") || !strings.HasSuffix(got.stdout, "FAIL\n") || !strings.Contains(got.stdout, "beta ran\n") {
		t.Fatalf("Runner %+v; want TestAlpha's failure, TestBeta still run and exit status 1", got)
	}
}

// After the transfer the program's bindings ARE the retained backing: reads
// through them (len, index, a field of an element) observe the slices M
// holds, before and after M.Run consumed them.
func TestGoSourceS243GeneratedTestMainRetainsAliases(t *testing.T) {
	source := strings.Replace(s243GeneratedDriver, "\tos.Exit(m.Run())\n",
		"\tfmt.Println(len(tests), len(benchmarks), tests[1].Name)\n\tcode := m.Run()\n\tfmt.Println(len(tests), tests[0].Name, code)\n\tos.Exit(code)\n", 1)
	got, err := runGoSourceTestMain(t, source, true)
	if err != nil {
		t.Fatalf("Runner: %v; stderr: %s", err, got.stderr)
	}
	want := goSourceOutcome{stdout: "2 0 TestBeta\nalpha ran\nbeta ran\nPASS\n2 TestAlpha 0\n"}
	if got != want {
		t.Fatalf("Runner %+v; want %+v", got, want)
	}
}

// refusedGoSourceTestMain runs source under the fact and requires the run to
// stop with the given refusal, reported either as the runner's error or on
// stderr with a non-zero status.
func refusedGoSourceTestMain(t *testing.T, source, refusal string) {
	t.Helper()
	got, err := runGoSourceTestMain(t, source, true)
	text := got.stderr
	if err != nil {
		text += "\n" + err.Error()
	}
	if err == nil && got.status == 0 || !strings.Contains(text, refusal) {
		t.Fatalf("Runner %+v, err %v; want refusal %q", got, err, refusal)
	}
	if strings.Contains(got.stdout, "PASS") || strings.Contains(got.stdout, "ran") {
		t.Fatalf("the program ran past the refusal: %+v", got)
	}
}

// Negative controls. Without the fact the driver cannot even import
// testing/internal/testdeps; with it, an argument that is not the bare
// binding is a distinct header the transfer cannot rebind, so the
// copied-reference refusal stays; and a slice of interpreter-owned elements
// under a callback-reaching consumer is refused exactly as before the
// transfer existed, fact or no fact.
func TestGoSourceS243GeneratedTestMainTransferNegatives(t *testing.T) {
	const copied = "original callback with copied slice references is unsupported"
	t.Run("the fact is required", func(t *testing.T) {
		_, err := runGoSourceTestMain(t, s243GeneratedDriver, false)
		if err == nil || !strings.Contains(err.Error(), "testing/internal/testdeps") {
			t.Fatalf("err = %v, want the internal-import refusal", err)
		}
	})
	t.Run("a sub-slice is not the binding", func(t *testing.T) {
		source := strings.Replace(s243GeneratedDriver, "testdeps.TestDeps{}, tests,", "testdeps.TestDeps{}, tests[:],", 1)
		if source == s243GeneratedDriver {
			t.Fatal("driver no longer spells the MainStart call")
		}
		refusedGoSourceTestMain(t, source, copied)
	})
	t.Run("interpreter-owned elements stay refused", func(t *testing.T) {
		refusedGoSourceTestMain(t, `package main

import (
	"fmt"
	"testing/internal/testdeps"
)

type item struct{ n int }

func (i item) String() string { return fmt.Sprint("item", i.n) }

var items = []item{{1}, {2}}

func main() {
	_ = testdeps.TestDeps{}
	fmt.Println(items)
	fmt.Println("ran")
}
`, copied)
	})
}
