// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:0
//
//line asm-backed.go:3:1
func Add(a, b int) int

// lower:2
//
//line asm-backed.go:5:1
func Twice(x int) int {
	// lower:1
//line asm-backed.go:6:2
	return Add(x, x)
}

// lower:4
//
//line asm-backed.go:9:1
func main() {
	// lower:3
//line asm-backed.go:10:2
	println(Twice(21))
}
