// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

import _ "unsafe"

// lower:0
//
//line directives.go:5:1
//go:noescape
//line directives.go:6:1
func Load(p *uint64) uint64

// lower:1
//
//line directives.go:8:1
//go:nosplit
//go:noescape
//line directives.go:10:1
func Store(p *uint64, v uint64)

// lower:2
//
//line directives.go:12:1
//go:linkname nanotime runtime.nanotime
//line directives.go:13:1
func nanotime() int64

// lower:6
//
//line directives.go:15:1
func main() {
	// lower:3
//line directives.go:16:2
	var x uint64
	// lower:4
//line directives.go:17:2
	Store(&x, x)
	// lower:5
//line directives.go:18:2
	println(Load(&x), nanotime())
}
