// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:0
//
//line method.go:3:1
type Vec struct{ x, y float64 }

// lower:1
//
//line method.go:5:1
func (v Vec) Dot(w Vec) float64

// lower:2
//
//line method.go:7:1
func (*Vec) Scale(k float64)

// lower:4
//
//line method.go:9:1
func (v Vec) Norm() float64 {
	// lower:3
//line method.go:10:2
	return v.Dot(v)
}

// lower:8
//
//line method.go:13:1
func main() {
	// lower:5
//line method.go:14:2
	var v Vec
	// lower:6
//line method.go:15:2
	v.Scale(2)
	// lower:7
//line method.go:16:2
	println(v.Norm())
}
