// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:2
//
//line with-body.go:3:1
func Add(a, b int) int {
	// lower:1
//line with-body.go:4:2
	return a + b
}

// lower:4
//
//line with-body.go:7:1
func (v Vec) Dot(w Vec) float64 {
	// lower:3
//line with-body.go:8:2
	return v.x*w.x + v.y*w.y
}

// lower:0
//
//line with-body.go:11:1
type Vec struct{ x, y float64 }

// lower:6
//
//line with-body.go:13:1
func main() {
	// lower:5
//line with-body.go:14:2
	println(Add(1, 2), Vec{1, 2}.Dot(Vec{3, 4}))
}
