//go:build ignore

// gen_go127stdlib creates the parser's closed Go 1.27 standard-library
// inventory. It intentionally inventories every supported target, so the
// parser result does not depend on the host running it.
package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const (
	toolchainVersion = "go1.27.0"
	// sourceSHA256 authenticates the complete src/ tree used during review.
	// Regeneration must fail until a changed source snapshot is reviewed.
	sourceSHA256    = "636d109763f0fe3e45347b74e07a0e00a1ca6a90b6130564b09ed8a04804d942"
	inventorySHA256 = "de444f71390a90f274b5176d8da92480ab72e2992d8885823712cd927e289f6c"
)

var moduleSums = map[string]string{
	"darwin-amd64": "h1:IzMA5UWIaARsT0Meuwbuhn57MLx3voSn0P2gTZQr/y8=",
	"darwin-arm64": "h1:QFUhEu+WNZ4lGI/0ual1EOKBq/Z/df/cL75PkCW8m1k=",
	"linux-amd64":  "h1:fVts2HjYwzBWrJtkf1B9HRDAuCZcZLexWI6ZX6Ls/IU=",
	"linux-arm64":  "h1:j3YFWnbfYYDouN9SH55CdTuBmwMifUuKLBqZhkRRcHc=",
}

func run(goBin string, env []string, args ...string) string {
	cmd := exec.Command(goBin, args...)
	cmd.Env = env
	out, err := cmd.Output()
	if err != nil {
		panic(fmt.Sprintf("%s %s: %v", goBin, strings.Join(args, " "), err))
	}
	return strings.TrimSpace(string(out))
}

func main() {
	env := append(os.Environ(), "GOTOOLCHAIN="+toolchainVersion)
	goBin := "go"
	if got := run(goBin, env, "version"); !strings.HasPrefix(got, "go version "+toolchainVersion+" ") {
		panic("unreviewed toolchain: " + got)
	}
	root := run(goBin, env, "env", "GOROOT")
	verifyModuleSum(goBin, env)
	gotSourceSHA := hashTree(filepath.Join(root, "src"))
	if sourceSHA256 != "" && gotSourceSHA != sourceSHA256 {
		panic(fmt.Sprintf("Go %s source checksum %s is not reviewed; want %s", toolchainVersion, gotSourceSHA, sourceSHA256))
	}

	imports := make(map[string]bool)
	for _, target := range strings.Fields(run(goBin, env, "tool", "dist", "list")) {
		goos, goarch, ok := strings.Cut(target, "/")
		if !ok {
			panic("invalid dist target: " + target)
		}
		targetEnv := append(append([]string{}, env...), "GOOS="+goos, "GOARCH="+goarch, "CGO_ENABLED=0")
		for _, path := range strings.Fields(run(goBin, targetEnv, "list", "std")) {
			if publicStdlibPath(path) {
				imports[path] = true
			}
		}
	}
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	inventoryBytes := []byte(strings.Join(paths, "\n") + "\n")
	gotInventorySHA := fmt.Sprintf("%x", sha256.Sum256(inventoryBytes))
	if gotInventorySHA != inventorySHA256 {
		panic(fmt.Sprintf("Go %s public package inventory checksum %s is not reviewed; want %s", toolchainVersion, gotInventorySHA, inventorySHA256))
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Source: sum.golang.org-authenticated Go %s toolchain module; src/ SHA256 %s.\n\n", toolchainVersion, gotSourceSHA)
	fmt.Fprintln(&out, "package syntax\n")
	fmt.Fprintf(&out, "const go127StdlibSourceSHA256 = %q\n\n", gotSourceSHA)
	fmt.Fprintln(&out, "var go127StdlibImports = [...]string{")
	for _, path := range paths {
		fmt.Fprintf(&out, "\t%q,\n", path)
	}
	fmt.Fprintln(&out, "}")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("go127stdlib_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func verifyModuleSum(goBin string, env []string) {
	platform := runtime.GOOS + "-" + runtime.GOARCH
	want, ok := moduleSums[platform]
	if !ok {
		panic("no reviewed Go 1.27 module sum for generator platform " + platform)
	}
	version := "v0.0.1-go1.27.0." + platform
	modCache := run(goBin, env, "env", "GOMODCACHE")
	zipHash := filepath.Join(modCache, "cache", "download", "golang.org", "toolchain", "@v", version+".ziphash")
	got, err := os.ReadFile(zipHash)
	if err != nil {
		panic(fmt.Sprintf("read authenticated module sum %s: %v", zipHash, err))
	}
	if strings.TrimSpace(string(got)) != want {
		panic(fmt.Sprintf("Go %s module sum %q is not reviewed; want %q", toolchainVersion, strings.TrimSpace(string(got)), want))
	}
}

func publicStdlibPath(path string) bool {
	if path == "builtin" || path == "unsafe" {
		return path == "unsafe"
	}
	if path == "cmd" || strings.HasPrefix(path, "cmd/") {
		return false
	}
	for _, part := range strings.Split(path, "/") {
		if part == "internal" || part == "vendor" || part == "testdata" || strings.HasSuffix(part, "_test") {
			return false
		}
	}
	return true
}

func hashTree(root string) string {
	var names []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() {
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			names = append(names, filepath.ToSlash(rel))
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	sort.Strings(names)
	h := sha256.New()
	for _, name := range names {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(h, "%d:%s:%d:", len(name), name, len(data))
		h.Write(data)
	}
	return fmt.Sprintf("%x", h.Sum(nil))
}
