package audit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestAuditCorpus runs the S154.3 parser-exclusive causal audit over
// roots.txt and rewrites FINDINGS.md. It runs only when BASHPP_AUDIT_CORPUS
// names the upstream go/test tree; otherwise it skips. An existing
// "## Spike S" section of FINDINGS.md (written by the out-of-tree spike) is
// preserved verbatim.
func TestAuditCorpus(t *testing.T) {
	corpus := os.Getenv("BASHPP_AUDIT_CORPUS")
	if corpus == "" {
		t.Skip("BASHPP_AUDIT_CORPUS not set; audit skipped")
	}
	rootsFile := os.Getenv("BASHPP_AUDIT_ROOTS")
	if rootsFile == "" {
		rootsFile = "roots.txt"
	}
	roots, err := ReadRoots(rootsFile)
	if err != nil {
		t.Fatal(err)
	}
	var results []Result
	var loadErrs []string
	for _, root := range roots {
		spec, err := LoadRoot(corpus, root)
		if err != nil {
			loadErrs = append(loadErrs, err.Error())
			continue
		}
		res, err := Audit(spec)
		if err != nil {
			loadErrs = append(loadErrs, err.Error())
			continue
		}
		results = append(results, res)
		t.Logf("%-32s %-8s %-13s wants=%d diags=%d failures=%d", root, res.FirstStage(), res.FirstClass(), res.NWants, res.NDiags, len(res.Failures))
	}
	findings := filepath.Join("FINDINGS.md")
	spike := ""
	if old, err := os.ReadFile(findings); err == nil {
		if i := strings.Index(string(old), "\n## Spike S"); i >= 0 {
			spike = string(old[i:])
		}
	}
	if err := os.WriteFile(findings, []byte(Render(results, loadErrs)+spike), 0o644); err != nil {
		t.Fatal(err)
	}
}

func md(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ⏎ ")
	if len(s) > 110 {
		s = s[:107] + "..."
	}
	return "`" + s + "`"
}

// Render writes the Part 1 findings.
func Render(results []Result, loadErrs []string) string {
	var b strings.Builder
	b.WriteString("# Sprint 154 — S154.3 parser-exclusive causal audit (findings only)\n\n")
	b.WriteString("Generated by `BASHPP_AUDIT_CORPUS=<go/test> go test ./gosource/testdata/sprint154/parser/` — an AUDIT, not a gate.\n")
	b.WriteString("Corpus: Go 1.27.0 `go/test`; roots: `roots.txt` (the 83 non-optimizer `errorcheck` roots of Sprint 154).\n")
	b.WriteString("Front end: `gosource.Load` with default `Options` (the `--check` path). Expectations collected per upstream\n")
	b.WriteString("`cmd/internal/testdir/testdir_test.go` wantedErrors/errorCheck (rules quoted in `audit.go`).\n\n")
	b.WriteString("Stage = component that produced the first wrong diagnostic (scanner < parser < checker). Class = the first failure in that stage.\n")
	b.WriteString("Notes: `chk-after-syn` = the root has syntax diagnostics AND go/types diagnostics (gc stops at syntax errors); `dup=n` = n diagnostics matched an expectation already satisfied on the same line (upstream tolerates these); `related=n` = n go/types related-info parts (`\\tprevious case` …) folded into their main diagnostic as gc prints them — `ErrorList.Error()` prints them as standalone `file:line:col: \\t…` lines, which the upstream harness would count as Unmatched Errors.\n\n")

	b.WriteString("## Counts (stage × class, first failure per root)\n\n")
	b.WriteString(Tally(results).Table())
	b.WriteString("\n")

	b.WriteString("## Rows\n\n")
	b.WriteString("| root | header | stage | class | expected (first failing) | got (first failing line) | notes |\n|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		want, got, line := "", "", ""
		if len(r.Failures) > 0 {
			f := r.Failures[0]
			want, got = f.Want, f.Got
			line = fmt.Sprintf("L%d", f.Line)
		}
		var notes []string
		if r.CheckerAfterSyntax {
			notes = append(notes, "chk-after-syn")
		}
		if r.RelatedFolded > 0 {
			notes = append(notes, fmt.Sprintf("related=%d", r.RelatedFolded))
		}
		if r.DupMatched > 0 {
			notes = append(notes, fmt.Sprintf("dup=%d", r.DupMatched))
		}
		if n := len(r.Failures); n > 1 {
			notes = append(notes, fmt.Sprintf("+%d more", n-1))
		}
		w := ""
		if want != "" {
			w = line + " " + md(want)
		} else if line != "" {
			w = line + " (none)"
		}
		g := ""
		if got != "" {
			g = md(got)
		} else if line != "" {
			g = "(no diagnostic)"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s | %s | %s |\n", r.Root, strings.TrimPrefix(r.Header, "// "), r.FirstStage(), r.FirstClass(), w, g, strings.Join(notes, ", "))
	}
	b.WriteString("\n")

	b.WriteString("## Wording-only parser/scanner rows\n\n")
	b.WriteString("Roots whose every failure is a scanner/parser diagnostic in class `wording` — the rows a different parser wording alone would close.\n\n")
	n := 0
	for _, r := range results {
		if len(r.Failures) == 0 {
			continue
		}
		only := true
		for _, f := range r.Failures {
			if f.Stage == StageChecker || f.Class != ClassWording {
				only = false
			}
		}
		if only {
			n++
			f := r.Failures[0]
			fmt.Fprintf(&b, "- %s — L%d want %s got %s\n", r.Root, f.Line, md(f.Want), md(f.Got))
		}
	}
	fmt.Fprintf(&b, "\nwording-only parser/scanner rows: %d\n\n", n)

	b.WriteString("## Failure detail (every failure, per root)\n\n")
	for _, r := range results {
		if len(r.Failures) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s (%s/%s; %d wants, %d diagnostics)\n\n", r.Root, r.FirstStage(), r.FirstClass(), r.NWants, r.NDiags)
		for _, f := range r.Failures {
			fmt.Fprintf(&b, "- %s/%s L%d", f.Stage, f.Class, f.Line)
			if f.Want != "" {
				fmt.Fprintf(&b, " want %s", md(f.Want))
			}
			if f.Got != "" {
				fmt.Fprintf(&b, " got %s", md(f.Got))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	if len(loadErrs) > 0 {
		b.WriteString("## Roots not audited\n\n")
		for _, e := range loadErrs {
			fmt.Fprintf(&b, "- %s\n", e)
		}
		b.WriteString("\n")
	}
	return b.String()
}
