package lower

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"
	"time"

	"mvdan.cc/sh/v3/expand"
	"mvdan.cc/sh/v3/interp"
	"mvdan.cc/sh/v3/syntax"
)

// The method hooks are proven the way the rest of this package proves a runtime
// slice: the emitted Go is built into a real binary, the source is deleted, and
// the binary is run against an empty PATH and compared with the engine running
// the same Bash++ program — exact stdout, exact stderr and exact status. A test
// that only searched the emitted text for substrings would have accepted Go
// that does not parse, so nothing here asserts on emitted text alone.
//
// methodUnit is the test's stand-in for the three delegations a dispatcher owner
// adds: a method declaration to runtimeMethodFunction, a method call to
// runtimeMethodCall, and a captured method value to runtimeMethodHandle. Every
// other statement is lowered by the ordinary emitter, so the artifacts differ
// from a fully wired compiler only in who chose those three branches.
type methodUnit struct {
	e *emitter
	// receivers is the static receiver type a call site resolves, which a wired
	// dispatcher reads from its projections. Declared variables are enough for
	// these fixtures and keep the resolution visible in the test.
	receivers map[string]string
	blocks    int
}

func newMethodUnit(file *syntax.File) *methodUnit {
	e := &emitter{
		options:         Options{Package: "main", Runtime: DefaultRuntime},
		prefix:          "__bpp0_",
		writtenNames:    map[string]bool{},
		inferredParams:  map[*syntax.BashPPField]string{},
		declaredTypes:   map[string]*syntax.BashPPDecl{},
		functionDecls:   map[string]*syntax.BashPPFuncDecl{},
		enumMembers:     map[string][]*syntax.Lit{},
		funcs:           map[string]bool{},
		scopes:          []map[string]bool{{}},
		globals:         map[string]bool{},
		visibleGlobals:  map[string]bool{},
		imports:         map[string]string{},
		callableParams:  map[*syntax.BashPPField]string{},
		dotNames:        map[string]bool{},
		declaredGlobals: map[string]bool{},
		typeNames:       map[string]bool{},
	}
	e.projections.projectionPush()
	e.needsExecution(file)
	e.findProjectionWrites(file)
	for _, s := range file.Stmts {
		if f, ok := s.Cmd.(*syntax.BashPPFuncDecl); ok {
			if f.Receiver != nil {
				e.methodDeclarations = append(e.methodDeclarations, f)
			} else {
				e.funcs[f.Name.Value] = true
				e.functionDecls[f.Name.Value] = f
			}
		}
		switch n := s.Cmd.(type) {
		case *syntax.BashPPDecl:
			if n.Kw.Value == "type" {
				e.typeNames[n.Name.Value] = true
				e.declaredTypes[n.Name.Value] = n
			}
			if n.Kw.Value == "var" || n.Kw.Value == "const" {
				e.globals[n.Name.Value] = true
			}
		case *syntax.BashPPShortDecl:
			for _, name := range names(n.Lhs) {
				if name != "_" {
					e.globals[name] = true
				}
			}
		}
	}
	return &methodUnit{e: e, receivers: map[string]string{}}
}

// compile lowers a whole unit. It is a reduced compilePass: the same
// declaration/body split and the same program main, with the method branches
// added.
func (u *methodUnit) compile(file *syntax.File) ([]byte, error) {
	e := u.e
	if !e.execution {
		return nil, fmt.Errorf("fixture does not reach the execution runtime")
	}
	if err := e.discoverCallableParams(file); err != nil {
		return nil, err
	}
	var declarations, body strings.Builder
	for _, s := range file.Stmts {
		switch n := s.Cmd.(type) {
		case *syntax.BashPPFuncDecl:
			text, err := u.function(n)
			if err != nil {
				return nil, err
			}
			declarations.WriteString(text)
		case *syntax.BashPPDecl:
			if n.Kw.Value == "type" {
				typ, err := e.declarationType(n)
				if err != nil {
					return nil, err
				}
				declarations.WriteString(e.mark(n) + typ + "\n")
				continue
			}
			if n.DeclType != nil {
				u.receivers[n.Name.Value] = n.DeclType.Value
			}
			text, err := e.globalStatement(s)
			if err != nil {
				return nil, err
			}
			body.WriteString(text)
		default:
			text, err := u.statement(s)
			if err != nil {
				return nil, err
			}
			body.WriteString(text)
		}
	}
	var raw strings.Builder
	fmt.Fprintf(&raw, "// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.\npackage main\n")
	e.output = true
	fmt.Fprintf(&raw, "import %sfmt \"fmt\"\n", e.prefix)
	fmt.Fprintf(&raw, "import %srt %s\n", e.prefix, strconv.Quote(e.options.Runtime))
	fmt.Fprintf(&raw, "import %sos \"os\"\n", e.prefix)
	raw.WriteString(e.importLines())
	if len(e.globals) > 0 {
		fmt.Fprintf(&raw, "var %sprogram *%srt.Program\n", e.prefix, e.prefix)
	}
	raw.WriteString(e.globalDecls.String())
	raw.WriteString(declarations.String())
	raw.WriteString(e.programMain(body.String()))
	text := strings.ReplaceAll(raw.String(), "/*"+e.prefix+"reset*/", e.program()+".SetStatus(0)\n")
	text = strings.ReplaceAll(text, "/*"+e.prefix+"status0*/", e.program()+".SetStatus(0);")
	text = strings.ReplaceAll(text, "/*"+e.prefix+"status1*/", e.program()+".SetStatus(1);")
	source, err := format.Source([]byte(text))
	if err != nil {
		return nil, fmt.Errorf("emitted Go does not parse: %w\n%s", err, text)
	}
	return source, nil
}

// function lowers a declaration, routing a method to runtimeMethodFunction with
// the same prologue e.function establishes for a free callable.
func (u *methodUnit) function(f *syntax.BashPPFuncDecl) (string, error) {
	e := u.e
	if f.Receiver == nil {
		return e.function(f)
	}
	saved, savedProjections, savedFunc := e.scopes, e.projections, e.inFunc
	e.inFunc = true
	e.projections = projector{}
	e.projections.projectionPush()
	e.projections.projectionPush()
	e.scopes = []map[string]bool{{}}
	defer func() { e.scopes, e.projections, e.inFunc = saved, savedProjections, savedFunc }()
	name, typ := receiverSpelling(f.Receiver)
	e.bind(name)
	e.projections.projectionBind(name, e.projectionType(typ, nil))
	// A method's own type parameters are in scope over its signature and body
	// exactly as a free callable's are; e.function binds them the same way.
	for _, p := range f.TypeParams {
		for _, n := range p.Names {
			e.bind(n.Value)
		}
	}
	signature, err := e.signature(f.Params, f.Results, f.Body)
	if err != nil {
		return "", err
	}
	savedResults := e.resultTypes
	e.resultTypes = e.returnTypes(f.Results)
	defer func() { e.resultTypes = savedResults }()
	body, err := e.block(f.Body)
	if err != nil {
		return "", err
	}
	generics, err := e.typeParams(f.TypeParams)
	if err != nil {
		return "", err
	}
	return e.runtimeMethodFunction(f, signature, body, generics)
}

func (u *methodUnit) statement(s *syntax.Stmt) (string, error) {
	e := u.e
	switch n := s.Cmd.(type) {
	case *syntax.BashPPAgenticBlock:
		child := fmt.Sprintf("%sblockProgram%d", e.prefix, u.blocks)
		u.blocks++
		parent := e.program()
		previous := e.programExpr
		e.programExpr = child
		defer func() { e.programExpr = previous }()
		var inner strings.Builder
		for _, stmt := range n.Body.Stmts {
			text, err := u.statement(stmt)
			if err != nil {
				return "", err
			}
			inner.WriteString(text)
		}
		return e.mark(n) + child + " := " + parent + ".Block()\n_ = " + child + "\n" + inner.String(), nil
	case *syntax.BashPPCall:
		if len(n.Fun) != 2 {
			break
		}
		text, err := e.runtimeMethodCall(n, u.receivers[n.Fun[0].Value])
		if err != nil {
			return "", err
		}
		return e.mark(n) + text + "\n", nil
	case *syntax.BashPPShortDecl:
		if n.Call != nil && len(n.Call.Fun) == 2 {
			rhs, err := e.runtimeMethodCall(n.Call, u.receivers[n.Call.Fun[0].Value])
			if err != nil {
				return "", err
			}
			ns := names(n.Lhs)
			for i, name := range ns {
				e.bind(name)
				e.projections.projectionBind(name, e.callProjection(n.Call, i))
			}
			return e.mark(n) + e.program() + ".SetStatus(0)\n" + strings.Join(ns, ", ") + " := " + rhs + e.unused(ns) + "\n", nil
		}
		if len(n.MethodValue) != 2 || len(n.Lhs) != 1 {
			break
		}
		receiver, method := n.MethodValue[0].Value, n.MethodValue[1].Value
		typ, err := e.runtimeMethodHandleType(n, u.receivers[receiver], method)
		if err != nil {
			return "", err
		}
		handle, err := e.runtimeMethodHandle(n, receiver, u.receivers[receiver], method)
		if err != nil {
			return "", err
		}
		target := n.Lhs[0].Value
		e.globalDecls.WriteString(e.mark(n) + "var " + target + " " + typ + "\n")
		e.declaredGlobals[target] = true
		e.visibleGlobals[target] = true
		e.globals[target] = true
		return e.mark(n) + "/*" + e.prefix + "reset*/" + target + " = " + handle + "\n", nil
	}
	return e.statement(s)
}

// The agentic-block program is the frame a call inside it is checked against.
// A wired dispatcher reaches it through e.agenticBlock; the fixtures only need
// the same nesting, which u.statement above reproduces.

func parseMethodFixture(t *testing.T, source string) *syntax.File {
	t.Helper()
	file, err := syntax.NewParser(syntax.Variant(syntax.LangBashPP)).Parse(strings.NewReader(source), "methods.bpp")
	if err != nil {
		t.Fatal(err)
	}
	return file
}

func lowerMethodFixture(t *testing.T, source string) []byte {
	t.Helper()
	file := parseMethodFixture(t, source)
	unit := newMethodUnit(file)
	emitted, err := unit.compile(file)
	if err != nil {
		t.Fatal(err)
	}
	return emitted
}

type methodOutcome struct {
	stdout, stderr string
	status         int
}

// runMethodArtifact builds the emitted Go, removes the source so nothing but
// the binary can be observed, and runs it with no usable PATH.
func runMethodArtifact(t *testing.T, ctx context.Context, source []byte) methodOutcome {
	t.Helper()
	dir := t.TempDir()
	_, this, _, _ := runtime.Caller(0)
	root := filepath.Dir(filepath.Dir(this))
	module := "module methodartifact\n\ngo " + strings.TrimPrefix(runtime.Version(), "go") +
		"\n\nrequire mvdan.cc/sh/v3 v3.0.0\nreplace mvdan.cc/sh/v3 => " + filepath.ToSlash(root) + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(module), 0600); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(generated, source, 0600); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(dir, "program")
	build := exec.CommandContext(ctx, filepath.Join(runtime.GOROOT(), "bin", "go"), "build", "-mod=mod", "-o", binary, "generated.go")
	build.Dir = dir
	build.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s\n%s", err, out, source)
	}
	if err := os.Remove(generated); err != nil {
		t.Fatal(err)
	}
	command := exec.CommandContext(ctx, binary)
	command.Dir = t.TempDir()
	command.Env = []string{"PATH="}
	var stdout, stderr bytes.Buffer
	command.Stdout = &stdout
	command.Stderr = &stderr
	status := 0
	if err := command.Run(); err != nil {
		var exit *exec.ExitError
		if !errors.As(err, &exit) {
			t.Fatal(err)
		}
		status = exit.ExitCode()
	}
	return methodOutcome{stdout.String(), stderr.String(), status}
}

func runMethodEngine(t *testing.T, ctx context.Context, source string) methodOutcome {
	t.Helper()
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	runner, err := interp.New(interp.Lang(syntax.LangBashPP), interp.StdIO(nil, &stdout, &stderr),
		interp.Dir(dir), interp.Env(expand.ListEnviron("PATH=")))
	if err != nil {
		t.Fatal(err)
	}
	status := 0
	if err := runner.Run(ctx, parseMethodFixture(t, source)); err != nil {
		var exit interp.ExitStatus
		if !errors.As(err, &exit) {
			t.Fatal(err)
		}
		status = int(exit)
	}
	return methodOutcome{stdout.String(), stderr.String(), status}
}

// methodFixture is one Bash++ program with the observable behaviour the lowered
// artifact must reproduce byte for byte, plus the emitted Go the lowering must
// contain for that behaviour to have come from the method ABI rather than from
// a lucky ordinary call.
type methodFixture struct {
	name    string
	source  string
	stdout  string
	stderr  string
	status  int
	emitted []string
	absent  []string
}

func methodFixtures() []methodFixture {
	return []methodFixture{{
		name: "marked_allow_and_deny",
		source: `type T int
agentic func (v T) Show() { echo shown }
var v T = 1
agentic { v.Show(); }
v.Show()
echo after
`,
		stdout: "shown\nafter\n",
		stderr: "Show: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"func (v T) __bpp0_call_Show(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site) {",
			"func (v T) Show() {",
			"v.__bpp0_call_Show(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"Show\"})",
			"v.__bpp0_call_Show(__bpp0_program, __bpp0_rt.Site{Name: \"Show\"})",
		},
	}, {
		name: "distinct_receivers_share_a_name",
		source: `type A struct { n int }
type B struct { n int }
agentic func (a *A) tag(label string) { echo "A:$label" }
agentic func (b *B) tag(count int) { printf 'B:%d\n' "$count" }
var x A = A{}
var y B = B{}
agentic { x.tag(first); y.tag(2); }
x.tag(denied)
echo after
`,
		stdout: "A:first\nB:2\nafter\n",
		stderr: "tag: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"func (a *A) __bpp0_call_tag(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site, label string) {",
			"func (b *B) __bpp0_call_tag(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site, count int) {",
			"x.__bpp0_call_tag(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"tag\"}, \"first\")",
			"y.__bpp0_call_tag(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"tag\"}, 2)",
		},
	}, {
		name: "pointer_receiver_auto_addresses_a_value",
		source: `type Counter struct { n int }
agentic func (c *Counter) bump() { c.n = 7 }
func (c Counter) show() { printf 'show:%d\n' c.n }
var c Counter = Counter{}
c.bump()
printf 'denied:%d\n' c.n
agentic { c.bump(); }
c.show()
printf 'field:%d\n' c.n
`,
		stdout: "denied:0\nshow:7\nfield:7\n",
		stderr: "bump: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"func (c *Counter) __bpp0_call_bump(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site) {",
			"func (c Counter) __bpp0_call_show(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site) {",
			"c.__bpp0_call_bump(__bpp0_program, __bpp0_rt.Site{Name: \"bump\"})",
		},
	}, {
		name: "interface_resolves_the_marker",
		source: `type T int
agentic func (v T) Show() { echo shown }
type I interface { Show() }
var v T = 1
var i I = v
agentic { i.Show(); }
i.Show()
echo after
`,
		stdout: "shown\nafter\n",
		stderr: "Show: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"__bpp0_capability, __bpp0_ok := __bpp0_receiver.(interface {",
			"__bpp0_call_Show(*__bpp0_rt.Program, __bpp0_rt.Site)",
			"__bpp0_capability.__bpp0_call_Show(__bpp0_program, __bpp0_rt.Site{Name: \"Show\"})",
			"__bpp0_receiver.Show()",
		},
	}, {
		name: "handle_captures_once_and_uses_the_call_site",
		source: `type T int
agentic func (v T) Show() { echo shown }
var v T = 1
f := v.Show
agentic { f(); }
f()
echo after
`,
		stdout: "shown\nafter\n",
		stderr: "Show: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"var f func(*__bpp0_rt.Program, __bpp0_rt.Site)",
			"f = v.__bpp0_call_Show",
			"f(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"f\"})",
			"f(__bpp0_program, __bpp0_rt.Site{Name: \"f\"})",
		},
	}, {
		name: "handles_keep_each_receivers_own_signature",
		source: `type A struct { n int }
type B struct { n int }
agentic func (a *A) tag(label string) { echo "A:$label" }
agentic func (b *B) tag(count int) { printf 'B:%d\n' "$count" }
var x A = A{}
var y B = B{}
h := y.tag
g := x.tag
agentic { h(2); g(first); }
h(3)
echo after
`,
		stdout: "B:2\nA:first\nafter\n",
		stderr: "tag: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"var h func(*__bpp0_rt.Program, __bpp0_rt.Site, int)",
			"var g func(*__bpp0_rt.Program, __bpp0_rt.Site, string)",
			"h = y.__bpp0_call_tag",
			"g = x.__bpp0_call_tag",
		},
	}, {
		name: "handle_capture_follows_the_receivers_own_rule",
		source: `type Counter struct { n int }
agentic func (c *Counter) bump() { c.n = 7 }
func (c Counter) copied() { printf 'copied:%d\n' c.n }
func (c *Counter) shared() { printf 'shared:%d\n' c.n }
var c Counter = Counter{}
value := c.copied
pointer := c.shared
agentic { c.bump(); }
value()
pointer()
`,
		// A value receiver is copied when the handle is taken and a pointer one
		// is addressed, so the later mutation is invisible to the first handle
		// and visible to the second. Both are captured exactly once.
		stdout: "copied:0\nshared:7\n",
		emitted: []string{
			"value = c.__bpp0_call_copied",
			"pointer = c.__bpp0_call_shared",
		},
	}, {
		name: "generic_receiver",
		source: `type Box[T any] struct { v T }
agentic func (b *Box[T]) show() { echo boxed }
var b Box[int] = Box[int]{}
agentic { b.show(); }
b.show()
echo after
`,
		stdout: "boxed\nafter\n",
		stderr: "show: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"func (b *Box[T]) __bpp0_call_show(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site) {",
			"func (b *Box[T]) show() {",
			"b.__bpp0_call_show(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"show\"})",
		},
	}, {
		name: "promoted_from_an_embedded_receiver",
		source: `type Base struct { n int }
agentic func (b *Base) hello() { echo base }
type Outer struct { Base }
var o Outer = Outer{}
agentic { o.hello(); }
o.hello()
echo after
`,
		stdout: "base\nafter\n",
		stderr: "hello: agentic action requires an explicit agentic { ...; } scope\n",
		emitted: []string{
			"func (b *Base) __bpp0_call_hello(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site) {",
			"o.__bpp0_call_hello(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"hello\"})",
		},
	}, {
		name: "results_return_through_both_abis",
		source: `type Adder struct { n int }
agentic func (a *Adder) sum(x int, y int) (int, int) { return $((x + y)), x }
var a Adder = Adder{}
agentic { total, first := a.sum(2, 3); printf 'sum:%d:%d\n' "$total" "$first"; }
echo after
`,
		stdout: "sum:5:2\nafter\n",
		emitted: []string{
			"func (a *Adder) __bpp0_call_sum(__bpp0_program *__bpp0_rt.Program, __bpp0_site __bpp0_rt.Site, x int, y int) (int, int) {",
			"func (a *Adder) sum(x int, y int) (int, int) {",
			"a.__bpp0_call_sum(__bpp0_blockProgram0, __bpp0_rt.Site{Name: \"sum\"}, 2, 3)",
		},
	}}
}

// TestRuntimeMethodArtifactParity is the acceptance evidence: every fixture is
// built, stripped of its source, run with an empty PATH, and diffed against the
// engine.
func TestRuntimeMethodArtifactParity(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()
	for _, tc := range methodFixtures() {
		t.Run(tc.name, func(t *testing.T) {
			emitted := lowerMethodFixture(t, tc.source)
			for _, want := range tc.emitted {
				if !strings.Contains(string(emitted), want) {
					t.Fatalf("emitted Go is missing %q\n%s", want, emitted)
				}
			}
			for _, unwanted := range tc.absent {
				if strings.Contains(string(emitted), unwanted) {
					t.Fatalf("emitted Go still contains %q\n%s", unwanted, emitted)
				}
			}
			artifact := runMethodArtifact(t, ctx, emitted)
			engine := runMethodEngine(t, ctx, tc.source)
			if engine != (methodOutcome{tc.stdout, tc.stderr, tc.status}) {
				t.Fatalf("engine outcome %+v is not the declared one %+v", engine, methodOutcome{tc.stdout, tc.stderr, tc.status})
			}
			if artifact != engine {
				t.Fatalf("artifact %+v engine %+v\n%s", artifact, engine, emitted)
			}
		})
	}
}

// TestRuntimeMethodPublicABIIsOrdinaryGo builds a second package that calls the
// public methods as an ordinary Go consumer would. It proves the public method
// keeps its declared Go signature, that a marked method reached from outside a
// compiled program runs with assistance off, and that a denial is reported once
// rather than repeated by a fallback.
func TestRuntimeMethodPublicABIIsOrdinaryGo(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()
	emitted := lowerMethodFixture(t, `type Adder struct { n int }
agentic func (a *Adder) sum(x int, y int) (int, int) { return $((x + y)), x }
func (a *Adder) label(prefix string) string { return $prefix }
var a Adder = Adder{}
agentic { a.sum(1, 1); }
`)
	consumer := `package main

import (
	"fmt"
	"os"
)

type foreign struct{}

func (foreign) Show() {}

func main() {
	var a Adder
	total, first := a.sum(4, 5)
	label := a.label("tag")
	fmt.Fprintf(os.Stdout, "public:%d:%d:%s\n", total, first, label)
	var _ interface {
		sum(int, int) (int, int)
		label(string) string
	} = &a
	__bpp0_sourceMain()
}
`
	dir := t.TempDir()
	_, this, _, _ := runtime.Caller(0)
	root := filepath.Dir(filepath.Dir(this))
	module := "module methodconsumer\n\ngo " + strings.TrimPrefix(runtime.Version(), "go") +
		"\n\nrequire mvdan.cc/sh/v3 v3.0.0\nreplace mvdan.cc/sh/v3 => " + filepath.ToSlash(root) + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(module), 0600); err != nil {
		t.Fatal(err)
	}
	// The unit's own main is renamed so the consumer supplies the entry point
	// and the public methods are reached as a foreign Go caller reaches them.
	renamed := strings.Replace(string(emitted), "\nfunc main() {", "\nfunc __bpp0_sourceMain() {", 1)
	if renamed == string(emitted) {
		t.Fatal("emitted unit has no main to rename")
	}
	if err := os.WriteFile(filepath.Join(dir, "generated.go"), []byte(renamed), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "consumer.go"), []byte(consumer), 0600); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(dir, "program")
	build := exec.CommandContext(ctx, filepath.Join(runtime.GOROOT(), "bin", "go"), "build", "-mod=mod", "-o", binary, ".")
	build.Dir = dir
	build.Env = append(os.Environ(), "GOWORK=off", "GOTOOLCHAIN=local")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s\n%s", err, out, renamed)
	}
	for _, name := range []string{"generated.go", "consumer.go"} {
		if err := os.Remove(filepath.Join(dir, name)); err != nil {
			t.Fatal(err)
		}
	}
	command := exec.CommandContext(ctx, binary)
	command.Dir = t.TempDir()
	command.Env = []string{"PATH="}
	var stdout, stderr bytes.Buffer
	command.Stdout = &stdout
	command.Stderr = &stderr
	status := 0
	if err := command.Run(); err != nil {
		var exit *exec.ExitError
		if !errors.As(err, &exit) {
			t.Fatal(err)
		}
		status = exit.ExitCode()
	}
	// The public entry to a marked method is its own program, whose frame has
	// assistance off, so the ordinary Go call is denied exactly once and its
	// results are the zero values. An unmarked method has nothing to deny and
	// returns its result through the same public signature.
	if stdout.String() != "public:0:0:tag\n" {
		t.Fatalf("public ABI stdout %q\n%s", stdout.String(), renamed)
	}
	denials := strings.Count(stderr.String(), "agentic action requires an explicit agentic")
	if denials != 1 {
		t.Fatalf("want one denial, got %d: %q", denials, stderr.String())
	}
	if status != 0 {
		t.Fatalf("status %d stderr %q", status, stderr.String())
	}
}

// TestRuntimeMethodResolutionDiagnostics covers the resolution rules that a
// substring test cannot: a name shared by several receivers is never guessed
// at, and the interface's own specification supplies the capability signature.
func TestRuntimeMethodResolutionDiagnostics(t *testing.T) {
	source := `type A struct { n int }
type B struct { n int }
agentic func (a *A) tag(label string) { echo "A:$label" }
agentic func (b *B) tag(count int) { printf 'B:%d\n' "$count" }
type I interface { tag(string) }
var x A = A{}
var y B = B{}
agentic { x.tag(one); }
`
	file := parseMethodFixture(t, source)
	unit := newMethodUnit(file)
	e := unit.e
	call := &syntax.BashPPCall{Fun: []*syntax.Lit{{Value: "x"}, {Value: "tag"}}}

	// A resolved receiver picks that receiver's declaration and signature.
	got, err := e.runtimeMethodCall(call, "A")
	if err != nil {
		t.Fatal(err)
	}
	if want := "x.__bpp0_call_tag(__bpp0_program, __bpp0_rt.Site{Name:\"tag\"})"; got != want {
		t.Fatalf("got %q want %q", got, want)
	}
	if got, err := e.runtimeMethodCall(call, "*B"); err != nil || !strings.Contains(got, "x.__bpp0_call_tag") {
		t.Fatalf("pointer receiver spelling: %q %v", got, err)
	}

	// An unresolved receiver for a name two types declare is a diagnostic, not
	// a guess at the first declaration.
	_, err = e.runtimeMethodCall(call, "")
	var list ErrorList
	if !errors.As(err, &list) || len(list) == 0 || list[0].Code != CodeType {
		t.Fatalf("ambiguous receiver: %v", err)
	}
	if _, err := e.runtimeMethodHandle(call, "x", "", "tag"); !errors.As(err, &list) || list[0].Code != CodeType {
		t.Fatalf("ambiguous handle receiver: %v", err)
	}

	// The interface's specification is what the capability interface states,
	// so an implementation is recognised by that signature and not by A's.
	through, err := e.runtimeMethodCall(call, "I")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(through, "interface{ __bpp0_call_tag(*__bpp0_rt.Program, __bpp0_rt.Site, string) }") {
		t.Fatalf("capability interface: %s", through)
	}
	// A zero-result private call must return rather than fall through into the
	// public method, which would repeat the method's effects.
	if strings.Count(through, "return") != 2 {
		t.Fatalf("private branch does not return: %s", through)
	}
	if _, err := e.runtimeMethodCall(call, "I"); err != nil {
		t.Fatal(err)
	}
	if _, _, found, err := e.interfaceMethodTypes(mustInterface(t, e, "I"), "missing", map[*syntax.BashPPInterfaceType]bool{}); found || err != nil {
		t.Fatalf("unknown interface method: %v %v", found, err)
	}

	// A method this unit does not declare is an ordinary Go call with no
	// private ABI and therefore no assistance.
	foreign := &syntax.BashPPCall{Fun: []*syntax.Lit{{Value: "x"}, {Value: "Unknown"}}}
	if got, err := e.runtimeMethodCall(foreign, "A"); err != nil || got != "x.Unknown()" {
		t.Fatalf("foreign call: %q %v", got, err)
	}
	if _, err := e.runtimeMethodHandle(foreign, "x", "A", "Unknown"); !errors.As(err, &list) || list[0].Code != CodeUnsupported {
		t.Fatalf("foreign handle: %v", err)
	}
}

func mustInterface(t *testing.T, e *emitter, name string) *syntax.BashPPInterfaceType {
	t.Helper()
	iface, ok := e.interfaceDecl(name)
	if !ok {
		t.Fatalf("%s is not a declared interface", name)
	}
	return iface
}

// TestRuntimeMethodDeclarationDiagnostics keeps the declaration hook's refusals
// positioned rather than emitting Go that cannot compile.
func TestRuntimeMethodDeclarationDiagnostics(t *testing.T) {
	e := newMethodUnit(parseMethodFixture(t, "agentic { echo hi; }\n")).e
	var list ErrorList
	kw := &syntax.Lit{Value: "func"}
	if _, err := e.runtimeMethodFunction(&syntax.BashPPFuncDecl{Kw: kw, Name: &syntax.Lit{Value: "m"}}, "()", "", ""); !errors.As(err, &list) || list[0].Code != CodeUnsupported {
		t.Fatalf("missing receiver: %v", err)
	}
	// A method's OWN type parameters are lowered, not refused: Go 1.27 accepts
	// them. Both halves of the pair carry the list, and the wrapper
	// instantiates the private half explicitly so a parameter that appears
	// only in the results is still spelled.
	generic := &syntax.BashPPFuncDecl{
		Kw:         kw,
		Name:       &syntax.Lit{Value: "m"},
		Receiver:   &syntax.BashPPReceiver{Name: &syntax.Lit{Value: "v"}, RecvType: &syntax.Lit{Value: "T"}},
		TypeParams: []*syntax.BashPPTypeParam{{Names: []*syntax.Lit{{Value: "X"}}}},
	}
	got, err := e.runtimeMethodFunction(generic, "()", "", "[X any]")
	if err != nil {
		t.Fatalf("method type parameters: %v", err)
	}
	for _, want := range []string{
		"func (v T) " + e.methodPrivateName("m") + "[X any](",
		"func (v T) m[X any]()",
		"v." + e.methodPrivateName("m") + "[X](",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("generic method lowering = %q, want to contain %q", got, want)
		}
	}
	unnamed := &syntax.BashPPFuncDecl{
		Kw:       kw,
		Name:     &syntax.Lit{Value: "m"},
		Receiver: &syntax.BashPPReceiver{Name: &syntax.Lit{Value: "v"}, RecvType: &syntax.Lit{Value: "T"}},
		Params:   []*syntax.BashPPField{{FieldType: &syntax.Lit{Value: "int"}}},
	}
	if _, err := e.runtimeMethodFunction(unnamed, "(int)", "", ""); !errors.As(err, &list) || list[0].Code != CodeUnsupported {
		t.Fatalf("unnamed parameter: %v", err)
	}
	if _, err := e.runtimeMethodCall(&syntax.BashPPCall{Fun: []*syntax.Lit{{Value: "x"}}}, "A"); !errors.As(err, &list) || list[0].Code != CodeExpr {
		t.Fatalf("selector arity: %v", err)
	}
}

// TestRuntimeMethodForeignImplementationRunsWithoutAssistance covers the branch
// no Bash++ source can reach: an interface value whose dynamic type was never
// compiled by this compiler and therefore carries no private method. The
// capability assertion fails and the public method runs, with assistance off.
// It also pins the defect the private branch's return exists for — a marked
// method reached without an agentic caller is denied once, not twice.
func TestRuntimeMethodForeignImplementationRunsWithoutAssistance(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()
	file := parseMethodFixture(t, `type T int
agentic func (v T) Show() { echo shown }
type I interface { Show() }
agentic { echo warm; }
`)
	unit := newMethodUnit(file)
	e := unit.e
	var decl *syntax.BashPPFuncDecl
	for _, s := range file.Stmts {
		if f, ok := s.Cmd.(*syntax.BashPPFuncDecl); ok && f.Receiver != nil {
			decl = f
		}
	}
	method, err := unit.function(decl)
	if err != nil {
		t.Fatal(err)
	}
	call := &syntax.BashPPCall{Fun: []*syntax.Lit{{Value: "i"}, {Value: "Show"}}}
	e.programExpr = "block"
	inside, err := e.runtimeMethodCall(call, "I")
	if err != nil {
		t.Fatal(err)
	}
	handle, err := e.runtimeMethodHandle(call, "i", "I", "Show")
	if err != nil {
		t.Fatal(err)
	}
	handleType, err := e.runtimeMethodHandleType(call, "I", "Show")
	if err != nil {
		t.Fatal(err)
	}
	e.programExpr = "program"
	outside, err := e.runtimeMethodCall(call, "I")
	if err != nil {
		t.Fatal(err)
	}
	source := `package main

import (
	__bpp0_fmt "fmt"
	__bpp0_os "os"
	__bpp0_rt "mvdan.cc/sh/v3/lower/shellrt"
)

type T int
type I interface{ Show() }
type Foreign struct{}

func (Foreign) Show() { __bpp0_fmt.Println("foreign") }

` + method + `
func main() {
	__bpp0_program, err := __bpp0_rt.NewProgram()
	if err != nil {
		__bpp0_fmt.Fprintln(__bpp0_os.Stderr, err)
		__bpp0_os.Exit(1)
	}
	err = __bpp0_program.Run(func(program *__bpp0_rt.Program) {
		block := program.Block()
		var i I = T(1)
		` + inside + `
		var compiled ` + handleType + ` = ` + handle + `
		i = Foreign{}
		` + inside + `
		var foreign ` + handleType + ` = ` + handle + `
		i = T(1)
		` + outside + `
		i = Foreign{}
		` + outside + `
		compiled(block, __bpp0_rt.Site{Name: "Show"})
		foreign(block, __bpp0_rt.Site{Name: "Show"})
	})
	if err != nil {
		__bpp0_program.Fail(err)
	}
	if status := __bpp0_program.Status(); status != 0 {
		__bpp0_os.Exit(status)
	}
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		t.Fatalf("harness does not parse: %v\n%s", err, source)
	}
	got := runMethodArtifact(t, ctx, formatted)
	// The compiled implementation keeps its marker through the interface, the
	// foreign one has no marker to keep, and each handle resolves the branch its
	// receiver had when it was captured.
	want := methodOutcome{
		stdout: "shown\nforeign\nforeign\nshown\nforeign\n",
		stderr: "Show: agentic action requires an explicit agentic { ...; } scope\n",
	}
	if got != want {
		t.Fatalf("got %+v want %+v\n%s", got, want, formatted)
	}
}

// TestRuntimeGenericMethodLowering is the end-to-end shape of the Go 1.27
// independent method type parameter: the declaration lowers to a private and a
// public half that both carry the method's own list, and an explicitly
// instantiated call reaches the private half with the same instantiation.
func TestRuntimeGenericMethodLowering(t *testing.T) {
	const src = `type R int
agentic func (r R) M[T any](v T) T { return $v }
var r R = 1
agentic { r.M[int](7); }
`
	got := string(lowerMethodFixture(t, src))
	for _, want := range []string{
		"func (r R) __bpp0_call_M[T any](",
		"func (r R) M[T any](v T) T",
		"r.__bpp0_call_M[T](",
		"__bpp0_call_M[int](",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("lowered generic method = %q, want to contain %q", got, want)
		}
	}
}
