package lower

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"mvdan.cc/sh/v3/syntax"
)

type emitter struct {
	options Options
	prefix  string
	marks   []Mapping
	scopes  []map[string]bool
	funcs   map[string]bool
	bridge  bool
	output  bool
	inFunc  bool
}

// Compile returns canonical Go and mappings, or positioned diagnostics with no
// partial output. It never executes the input program.
func Compile(file *syntax.File, options Options) (*Result, error) {
	if file == nil {
		return nil, ErrorList{{Code: CodeUnsupported, Msg: "nil syntax file"}}
	}
	if options.Package == "" {
		options.Package = "main"
	}
	if options.Runtime == "" {
		options.Runtime = DefaultRuntime
	}
	if !token.IsIdentifier(options.Package) || token.Lookup(options.Package).IsKeyword() {
		return nil, ErrorList{{Code: CodeType, Msg: "invalid package name", Pos: file.Pos()}}
	}
	e := &emitter{options: options, funcs: map[string]bool{}, scopes: []map[string]bool{{}}}
	// Allocate private names from the tree rather than reserving user identifiers.
	for n := 0; ; n++ {
		e.prefix = fmt.Sprintf("__bpp%d_", n)
		used := false
		syntax.Walk(file, func(n syntax.Node) bool {
			if l, ok := n.(*syntax.Lit); ok && strings.Contains(l.Value, e.prefix) {
				used = true
			}
			return true
		})
		if !used {
			break
		}
	}
	for _, s := range file.Stmts {
		if f, ok := s.Cmd.(*syntax.BashPPFuncDecl); ok {
			e.funcs[f.Name.Value] = true
		}
	}
	var declarations, body strings.Builder
	for _, s := range file.Stmts {
		if f, ok := s.Cmd.(*syntax.BashPPFuncDecl); ok {
			if err := e.statementFlags(s); err != nil {
				return nil, err
			}
			text, err := e.function(f)
			if err != nil {
				return nil, err
			}
			declarations.WriteString(text)
		} else {
			text, err := e.statement(s)
			if err != nil {
				return nil, err
			}
			body.WriteString(text)
		}
	}
	imports := []string{}
	if e.output {
		imports = append(imports, "fmt")
	}
	if e.bridge {
		imports = append(imports, options.Runtime)
	}
	sort.Strings(imports)
	var raw strings.Builder
	fmt.Fprintf(&raw, "// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.\npackage %s\n", options.Package)
	if e.output {
		fmt.Fprintf(&raw, "import %sfmt \"fmt\"\n", e.prefix)
	}
	if e.bridge {
		fmt.Fprintf(&raw, "import %srt %s\n", e.prefix, strconv.Quote(options.Runtime))
	}
	raw.WriteString(declarations.String())
	tail := ""
	if e.bridge {
		tail = e.prefix + "rt.Exit()\n"
	}
	fmt.Fprintf(&raw, "func main() {\n%s%s}\n", body.String(), tail)
	reset := ""
	if e.bridge {
		reset = e.prefix + "rt.Status = 0\n"
	}
	rawText := strings.ReplaceAll(raw.String(), "/*"+e.prefix+"reset*/", reset)
	source, err := format.Source([]byte(rawText))
	if err != nil {
		return nil, e.fail(file, CodeExpr, "generated Go is not syntactically valid: "+err.Error())
	}
	result := &Result{Source: source, Package: options.Package, Imports: imports, Origin: options.Origin}
	// Markers survive gofmt; map the next nonempty emitted line. Markers carry
	// only ordinal IDs, never source filenames or host paths.
	pending := -1
	for i, line := range strings.Split(string(source), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "// lower:") {
			pending, _ = strconv.Atoi(strings.TrimPrefix(trimmed, "// lower:"))
			continue
		}
		if pending >= 0 && trimmed != "" {
			m := e.marks[pending]
			m.GoLine = i + 1
			m.GoCol = len(line) - len(strings.TrimLeft(line, "\t ")) + 1
			result.Mappings = append(result.Mappings, m)
			pending = -1
		}
	}
	// Native Go's checker supplies representability, arity and operator checks.
	// A synthetic bridge signature avoids loading module source or running tools.
	fs := token.NewFileSet()
	goFile, err := parser.ParseFile(fs, "generated.go", source, 0)
	if err != nil {
		return nil, e.fail(file, CodeExpr, err.Error())
	}
	var diagnostics ErrorList
	conf := types.Config{Importer: bridgeImporter{fallback: importer.Default(), path: options.Runtime}, Error: func(err error) {
		te, ok := err.(types.Error)
		pos := file.Pos()
		node := "File"
		if ok {
			line := fs.Position(te.Pos).Line
			for _, m := range result.Mappings {
				if m.GoLine > line {
					break
				}
				pos, node = m.Pos, m.Node
			}
		}
		msg := err.Error()
		if ok {
			msg = te.Msg
		}
		code := CodeType
		if strings.Contains(msg, "undefined:") {
			code = CodeUndefined
		}
		diagnostics = append(diagnostics, Diagnostic{Code: code, Msg: msg, Node: node, Pos: pos})
	}}
	_, _ = conf.Check(options.Package, fs, []*ast.File{goFile}, nil)
	if len(diagnostics) > 0 {
		sort.SliceStable(diagnostics, func(i, j int) bool { return diagnostics[i].Pos.Offset() < diagnostics[j].Pos.Offset() })
		return nil, diagnostics
	}
	return result, nil
}

type bridgeImporter struct {
	fallback types.Importer
	path     string
}

func (i bridgeImporter) Import(path string) (*types.Package, error) {
	if path != i.path {
		return i.fallback.Import(path)
	}
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, "bridge.go", `package shellrt
func Printf(format string,args ...any) error{return nil}
func Echo(args ...any) error{return nil}
func Word(v any) string{return ""}
func Fail(err error){}
func Exit(){}
var Status int
`, 0)
	if err != nil {
		return nil, err
	}
	return new(types.Config).Check(path, fs, []*ast.File{f}, nil)
}
func nodeName(n syntax.Node) string {
	if n == nil {
		return "nil"
	}
	return strings.TrimPrefix(reflect.TypeOf(n).String(), "*syntax.")
}
func (e *emitter) fail(n syntax.Node, code, msg string) error {
	var pos syntax.Pos
	if n != nil {
		pos = n.Pos()
	}
	return ErrorList{{Code: code, Msg: msg, Node: nodeName(n), Pos: pos}}
}
func (e *emitter) mark(n syntax.Node) string {
	id := len(e.marks)
	e.marks = append(e.marks, Mapping{Pos: n.Pos(), Node: nodeName(n)})
	return fmt.Sprintf("// lower:%d\n", id)
}
func (e *emitter) known(name string) bool {
	if e.funcs[name] {
		return true
	}
	for i := len(e.scopes) - 1; i >= 0; i-- {
		if e.scopes[i][name] {
			return true
		}
	}
	switch name {
	case "true", "false", "nil":
		return true
	}
	return false
}
func (e *emitter) bind(name string) {
	if name != "_" {
		e.scopes[len(e.scopes)-1][name] = true
	}
}
func (e *emitter) push() { e.scopes = append(e.scopes, map[string]bool{}) }
func (e *emitter) pop()  { e.scopes = e.scopes[:len(e.scopes)-1] }
func (e *emitter) statementFlags(s *syntax.Stmt) error {
	if s.Negated || s.Background || s.Coprocess || s.Disown || len(s.Redirs) > 0 {
		return e.fail(s, CodeUnsupported, "statement flags and redirections need the shell runtime slice")
	}
	return nil
}
func (e *emitter) statement(s *syntax.Stmt) (string, error) {
	if err := e.statementFlags(s); err != nil {
		return "", err
	}
	if s.Cmd == nil {
		return "", nil
	}
	text, err := e.command(s.Cmd)
	if err != nil {
		return "", err
	}
	reset := ""
	switch n := s.Cmd.(type) {
	case *syntax.BashPPDecl, *syntax.BashPPShortDecl, *syntax.BashPPAssign, *syntax.BashPPForAssign, *syntax.BashPPIncDec, *syntax.BashPPUpdate:
		reset = "/*" + e.prefix + "reset*/"
	case *syntax.BashPPReturn:
		if len(n.Results) > 0 {
			reset = "/*" + e.prefix + "reset*/"
		}
	}
	return e.mark(s.Cmd) + reset + text + "\n", nil
}
func (e *emitter) block(b *syntax.Block) (string, error) {
	e.push()
	defer e.pop()
	var out strings.Builder
	for _, s := range b.Stmts {
		x, err := e.statement(s)
		if err != nil {
			return "", err
		}
		out.WriteString(x)
	}
	return out.String(), nil
}
func names(lits []*syntax.Lit) []string {
	out := make([]string, len(lits))
	for i, l := range lits {
		out[i] = l.Value
	}
	return out
}
func (e *emitter) unused(ns []string) string {
	var out string
	for _, n := range ns {
		if n != "_" {
			out += "\n_ = " + n
		}
	}
	return out
}
func (e *emitter) function(f *syntax.BashPPFuncDecl) (string, error) {
	if f.Agentic != nil || f.Receiver != nil || len(f.TypeParams) > 0 {
		return "", e.fail(f, CodeUnsupported, "marked, generic and receiver functions need callable metadata lowering")
	}
	if f.Name.Value == "main" {
		return "", e.fail(f, CodeUnsupported, "explicit main function needs program-entry lowering")
	}
	// Package functions cannot see main locals. Do not accidentally resolve a
	// script-local name while lowering a package-level function.
	savedFunc := e.inFunc
	e.inFunc = true
	defer func() { e.inFunc = savedFunc }()
	saved := e.scopes
	e.scopes = []map[string]bool{{}}
	defer func() { e.scopes = saved }()
	params, err := e.fields(f.Params)
	if err != nil {
		return "", err
	}
	results, err := e.fields(f.Results)
	if err != nil {
		return "", err
	}
	body, err := e.block(f.Body)
	if err != nil {
		return "", err
	}
	result := ""
	if results != "" {
		result = " (" + results + ")"
	}
	return e.mark(f) + "func " + f.Name.Value + "(" + params + ")" + result + " {\n" + body + "}\n", nil
}
func scalarType(s string) bool {
	switch s {
	case "bool", "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "byte", "rune", "error", "any":
		return true
	}
	return false
}
func (e *emitter) fields(fs []*syntax.BashPPField) (string, error) {
	var out []string
	for _, f := range fs {
		if f.Default != nil || f.Ellipsis.IsValid() || f.FieldType == nil || !scalarType(f.FieldType.Value) {
			return "", e.fail(f, CodeUnsupported, "parameter/result type, default or variadic form not supported by foundation")
		}
		ns := names(f.Names)
		for _, n := range ns {
			e.bind(n)
		}
		s := strings.Join(ns, ",")
		if s != "" {
			s += " "
		}
		out = append(out, s+f.FieldType.Value)
	}
	return strings.Join(out, ", "), nil
}
func (e *emitter) command(c syntax.Command) (string, error) {
	switch n := c.(type) {
	case *syntax.BashPPDecl:
		if n.Kw.Value != "var" && n.Kw.Value != "const" {
			return "", e.fail(n, CodeUnsupported, "type declarations need the type lowering slice")
		}
		if len(n.TypeParams) > 0 || len(n.StructFields) > 0 || len(n.EnumMembers) > 0 {
			return "", e.fail(n, CodeUnsupported, "composite declaration")
		}
		typ := ""
		if n.DeclType != nil {
			if !scalarType(n.DeclType.Value) {
				return "", e.fail(n, CodeUnsupported, "non-scalar declaration type")
			}
			typ = " " + n.DeclType.Value
		}
		init := ""
		var err error
		if n.InitExpr != nil {
			init, err = e.expr(n.InitExpr)
		} else if len(n.Init) > 0 {
			init, err = e.wordSequence(n.Init)
		}
		if err != nil {
			return "", err
		}
		if init != "" {
			init = " = " + init
		}
		e.bind(n.Name.Value)
		return n.Kw.Value + " " + n.Name.Value + typ + init + e.unused([]string{n.Name.Value}), nil
	case *syntax.BashPPShortDecl:
		var rhs string
		var err error
		switch {
		case n.Call != nil:
			rhs, err = e.call(n.Call)
		case n.Expr != nil:
			rhs, err = e.expr(n.Expr)
		case n.FuncLit != nil || n.MakeChan != nil || n.Recv != nil || len(n.MethodValue) > 0:
			return "", e.fail(n, CodeUnsupported, "callable/channel declaration variant")
		default:
			rhs, err = e.wordSequence(n.Rhs)
		}
		if err != nil {
			return "", err
		}
		ns := names(n.Lhs)
		for _, name := range ns {
			e.bind(name)
		}
		return strings.Join(ns, ", ") + " := " + rhs + e.unused(ns), nil
	case *syntax.BashPPCall:
		return e.call(n)
	case *syntax.BashPPReturn:
		if n.FuncLit != nil {
			return "", e.fail(n, CodeUnsupported, "returned closure")
		}
		var values []string
		for _, w := range n.Results {
			x, err := e.valueWord(w)
			if err != nil {
				return "", err
			}
			values = append(values, x)
		}
		return "return " + strings.Join(values, ", "), nil
	case *syntax.BashPPForAssign:
		x, err := e.expr(n.Expr)
		return n.Name.Value + " = " + x, err
	case *syntax.BashPPAssign:
		if n.Call != nil {
			rhs, err := e.call(n.Call)
			if err != nil {
				return "", err
			}
			if len(n.Names) == 0 {
				return "", e.fail(n, CodeUnsupported, "structured call assignment")
			}
			return strings.Join(names(n.Names), ", ") + " = " + rhs, nil
		}
		if len(n.Names) > 0 {
			var rhs []string
			for _, x := range n.ValueExprs {
				v, err := e.expr(x)
				if err != nil {
					return "", err
				}
				rhs = append(rhs, v)
			}
			if len(rhs) == 0 {
				for _, w := range n.Values {
					v, err := e.valueWord(w)
					if err != nil {
						return "", err
					}
					rhs = append(rhs, v)
				}
			}
			return strings.Join(names(n.Names), ", ") + " = " + strings.Join(rhs, ", "), nil
		}
		if n.TargetExpr != nil && n.ValueExpr != nil {
			l, err := e.expr(n.TargetExpr)
			if err != nil {
				return "", err
			}
			r, err := e.expr(n.ValueExpr)
			return l + " = " + r, err
		}
		return "", e.fail(n, CodeUnsupported, "assignment variant lacks typed target/value")
	case *syntax.BashPPIncDec:
		target := ""
		var err error
		if n.Target != nil {
			target, err = e.expr(n.Target)
		} else if n.Name != nil {
			target = n.Name.Value
		} else {
			return "", e.fail(n, CodeUnsupported, "update target")
		}
		return target + n.Op.Value, err
	case *syntax.BashPPUpdate:
		if n.Target == nil || n.Value == nil {
			return "", e.fail(n, CodeExpr, "compound assignment lacks typed expressions")
		}
		l, err := e.expr(n.Target)
		if err != nil {
			return "", err
		}
		r, err := e.expr(n.Value)
		return l + " " + n.Op.Value + " " + r, err
	case *syntax.BashPPIf:
		return e.ifStmt(n)
	case *syntax.BashPPFor:
		return e.forStmt(n)
	case *syntax.BashPPBranch:
		return n.Kw.Value, nil
	case *syntax.BashPPDefer:
		return "", e.fail(n, CodeUnsupported, "defer needs shell status and agentic scheduling scope")
	case *syntax.Block:
		b, err := e.block(n)
		return "{\n" + b + "}", err
	case *syntax.CallExpr:
		return e.shell(n)
	default:
		return "", e.fail(c, CodeUnsupported, "certified node is not implemented by the foundation: "+nodeName(c))
	}
}
func (e *emitter) ifStmt(n *syntax.BashPPIf) (string, error) {
	e.push()
	defer e.pop()
	init := ""
	if n.Init != nil {
		x, err := e.command(n.Init)
		if err != nil {
			return "", err
		}
		init = x + "\n"
	}
	cond, err := e.expr(n.Cond)
	if err != nil {
		return "", err
	}
	body, err := e.block(n.Then)
	if err != nil {
		return "", err
	}
	out := "if " + cond + " {\n" + body + "}"
	if n.Else != nil {
		x, err := e.command(n.Else)
		if err != nil {
			return "", err
		}
		out += " else " + x
	}
	if init != "" {
		out = "{\n" + init + out + "\n}"
	}
	return out, nil
}
func (e *emitter) forStmt(n *syntax.BashPPFor) (string, error) {
	e.push()
	defer e.pop()
	init, post, cond := "", "", ""
	var err error
	if n.Init != nil {
		init, err = e.command(n.Init)
		if err != nil {
			return "", err
		}
	}
	if n.Post != nil {
		post, err = e.command(n.Post)
		if err != nil {
			return "", err
		}
	}
	if n.Cond != nil {
		cond, err = e.expr(n.Cond)
		if err != nil {
			return "", err
		}
	}
	body, err := e.block(n.Body)
	if err != nil {
		return "", err
	}
	header := cond
	if n.FirstSemi.IsValid() {
		header = "; " + cond + "; " + post
	}
	out := "for " + header + " {\n" + body + "}"
	if init != "" {
		out = "{\n" + init + "\n" + out + "\n}"
	}
	return out, nil
}
func (e *emitter) expr(x syntax.BashPPExpr) (string, error) {
	switch n := x.(type) {
	case *syntax.BashPPBasicLit:
		return n.Value.Value, nil
	case *syntax.BashPPIdent:
		if !e.known(n.Name.Value) {
			return "", e.fail(n, CodeUndefined, "undefined: "+n.Name.Value)
		}
		return n.Name.Value, nil
	case *syntax.BashPPParenExpr:
		v, err := e.expr(n.X)
		return "(" + v + ")", err
	case *syntax.BashPPUnaryExpr:
		v, err := e.expr(n.X)
		return "(" + n.Op.Value + v + ")", err
	case *syntax.BashPPBinaryExpr:
		l, err := e.expr(n.X)
		if err != nil {
			return "", err
		}
		r, err := e.expr(n.Y)
		return "(" + l + " " + n.Op.Value + " " + r + ")", err
	case *syntax.BashPPConvertExpr:
		if !scalarType(n.ConvType.Value) {
			return "", e.fail(n, CodeUnsupported, "non-scalar conversion")
		}
		v, err := e.expr(n.X)
		return n.ConvType.Value + "(" + v + ")", err
	default:
		return "", e.fail(x, CodeUnsupported, "typed expression not implemented: "+nodeName(x))
	}
}
func (e *emitter) call(c *syntax.BashPPCall) (string, error) {
	if c.FuncLit != nil || len(c.TypeArgs) > 0 || len(c.ArgNames) > 0 || c.Ellipsis.IsValid() || c.ArgType != nil || c.PointerMethodExpr {
		return "", e.fail(c, CodeUnsupported, "call variant needs callable/type lowering")
	}
	if len(c.Fun) != 1 {
		return "", e.fail(c, CodeUnsupported, "selector calls need import/method lowering")
	}
	name := c.Fun[0].Value
	if !e.funcs[name] && !scalarType(name) && name != "print" && name != "println" {
		return "", e.fail(c, CodeUndefined, "undefined callable: "+name)
	}
	var args []string
	for _, w := range c.Args {
		x, err := e.valueWord(w)
		if err != nil {
			return "", err
		}
		args = append(args, x)
	}
	if !e.funcs[name] && (name == "print" || name == "println") {
		e.output = true
		if name == "println" {
			return e.prefix + "fmt.Println(" + strings.Join(args, ", ") + ")", nil
		}
		for i, a := range args {
			args[i] = e.prefix + "fmt.Sprint(" + a + ")"
		}
		return e.prefix + "fmt.Print(" + strings.Join(args, ", ") + ")", nil
	}
	return name + "(" + strings.Join(args, ", ") + ")", nil
}
