package lower_test

import (
	"bytes"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"mvdan.cc/sh/v3/gosource"
	"mvdan.cc/sh/v3/lower"
)

// Sprint 152 decision D1: a Go-only input lowers to itself. The reproducers
// under testdata/sprint152/fidelity each isolate one rewrite class (spike F,
// FINDINGS.md); a class is closed when its generated Go, after gofmt and
// dropping the package clause, the "// lower:N" markers, their gofmt "//"
// separators and the "//line" directives, is byte-identical to the input.
// Classes not yet closed are listed in fidelityOpen and are still exercised
// so that their output stays gofmt-stable.
var fidelityOpen = map[string]bool{
	"comments-dropped":         true, // C1
	"sink-statements":          true, // C2
	"untyped-constants":        true, // C3
	"reparenthesised-exprs":    true, // C4
	"main-rename":              true, // C5
	"guard-prologue":           true, // C6
	"explicit-deref":           true, // C7
	"import-aliasing":          true, // C8
	"type-assertion":           true, // C9
	"synthetic-receiver-names": true, // C10
	"decl-reordering":          true, // C11
}

func TestGoSourceFidelity(t *testing.T) {
	dir := filepath.Join("testdata", "sprint152", "fidelity")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, ".generated.go") {
			continue
		}
		t.Run(strings.TrimSuffix(name, ".go"), func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join(dir, name))
			if err != nil {
				t.Fatal(err)
			}
			program, err := gosource.Parse(bytes.NewReader(data), name, gosource.Options{RunMain: true})
			if err != nil {
				t.Fatal(err)
			}
			result, err := lower.Compile(program.File, lower.Options{Origin: name})
			if err != nil {
				t.Fatal(err)
			}
			// Byte-determinism gate: the emitter's own output is gofmt-stable.
			formatted, err := format.Source(result.Source)
			if err != nil {
				t.Fatalf("generated Go is not gofmt-parseable: %v\n%s", err, result.Source)
			}
			if !bytes.Equal(formatted, result.Source) {
				t.Errorf("generated != gofmt(generated)\n--- generated\n%s\n--- gofmt\n%s", result.Source, formatted)
			}
			want := fidelityNormalize(t, data)
			got := fidelityNormalize(t, result.Source)
			if want != got {
				if fidelityOpen[strings.TrimSuffix(name, ".go")] {
					t.Skipf("class still open\n--- want\n%s\n--- got\n%s", want, got)
				}
				t.Errorf("generated Go is not the input\n--- want\n%s\n--- got\n%s\n--- raw\n%s", want, got, result.Source)
			} else if fidelityOpen[strings.TrimSuffix(name, ".go")] {
				t.Errorf("class is closed; drop it from fidelityOpen")
			}
		})
	}
}

// fidelityNormalize gofmts src and drops the package clause, the generated
// header, the "// lower:N" markers with their "//" separators and the
// "//line" directives.
func fidelityNormalize(t *testing.T, src []byte) string {
	t.Helper()
	formatted, err := format.Source(src)
	if err != nil {
		t.Fatalf("gofmt: %v\n%s", err, src)
	}
	var out []string
	marker := false
	for _, line := range strings.Split(string(formatted), "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "// lower:"):
			marker = true
			continue
		case marker && trimmed == "//":
			continue
		case strings.HasPrefix(trimmed, "//line "):
			marker = false
			continue
		case strings.HasPrefix(trimmed, "package "):
			marker = false
			continue
		case trimmed == "// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.":
			continue
		}
		marker = false
		out = append(out, line)
	}
	return strings.TrimSpace(strings.Join(out, "\n")) + "\n"
}
