package lower

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/scanner"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"

	"mvdan.cc/sh/v3/syntax"
)

func (e *emitter) libraryResult(file *syntax.File, options Options, globalTypes map[string]string, declarations []sourceDecl, bodies map[string]*strings.Builder) (*Result, error) {
	sort.SliceStable(declarations, func(i, j int) bool { return declarations[i].before(declarations[j]) })
	result := &Result{Sources: append([]syntax.SourceFile(nil), file.Sources...), Package: options.Package, Origin: options.Origin}
	seenNames := map[string]bool{}
	allImports := map[string]bool{}
	fs := token.NewFileSet()
	var goFiles []*ast.File
	for _, input := range file.Sources {
		if seenNames[input.Name] {
			return nil, e.fail(file, CodeUnsupported, "library emission requires distinct source names")
		}
		seenNames[input.Name] = true
		var raw strings.Builder
		fmt.Fprintf(&raw, "// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.\npackage %s\n", options.Package)
		var text strings.Builder
		for _, declaration := range declarations {
			if declaration.source == input.Name {
				text.WriteString(declaration.text)
			}
		}
		if body := bodies[input.Name]; body != nil && body.Len() > 0 {
			fmt.Fprintf(&text, "func init() {\n%s}\n", body.String())
		}
		imports, lines := e.libraryImportLines(input.Name, identifiersIn(text.String()))
		raw.WriteString(lines)
		for _, path := range imports {
			allImports[path] = true
		}
		raw.WriteString(text.String())
		source, err := format.Source([]byte(raw.String()))
		if err != nil {
			return nil, e.fail(file, CodeExpr, "generated Go is not syntactically valid: "+err.Error())
		}
		generated := FileResult{Name: input.Name, Source: source, Imports: imports, Mappings: e.sourceMappings(source)}
		parsed, err := parser.ParseFile(fs, input.Name, generated.Source, 0)
		if err != nil {
			return nil, e.fail(file, CodeExpr, err.Error())
		}
		goFiles = append(goFiles, parsed)
		result.Files = append(result.Files, generated)
	}
	for _, parsed := range goFiles {
		prepareCgoCheckerFile(parsed)
	}
	for path := range allImports {
		result.Imports = append(result.Imports, path)
	}
	sort.Strings(result.Imports)

	var diagnostics ErrorList
	conf := types.Config{FakeImportC: len(file.CgoPackages) > 0, Importer: bridgeImporter{fallback: e.moduleImporter, path: options.Runtime, cache: map[string]*types.Package{}, foreign: e.hasForeign()}, Error: func(err error) {
		te, ok := err.(types.Error)
		pos := file.Pos()
		node := "File"
		if ok {
			generatedPos := fs.Position(te.Pos)
			for _, output := range result.Files {
				if output.Name != generatedPos.Filename {
					continue
				}
				for _, mapping := range output.Mappings {
					if mapping.GoLine > generatedPos.Line {
						break
					}
					pos, node = mapping.Pos, mapping.Node
				}
			}
		}
		msg := err.Error()
		if ok {
			msg = te.Msg
		}
		code := CodeType
		if strings.Contains(msg, "undefined:") {
			code = CodeUndefined
		}
		origin, _ := file.SourceAt(pos)
		diagnostics = append(diagnostics, Diagnostic{Code: code, Msg: msg, Node: node, Pos: pos, Source: origin.Name})
	}}
	checked, _ := conf.Check(options.Package, fs, goFiles, nil)
	if len(diagnostics) > 0 {
		sort.SliceStable(diagnostics, func(i, j int) bool { return diagnostics[i].Pos.Offset() < diagnostics[j].Pos.Offset() })
		return nil, diagnostics
	}
	if globalTypes == nil && len(e.globals) > 0 {
		inferred := map[string]string{}
		for name := range e.globals {
			if obj := checked.Scope().Lookup(name); obj != nil {
				inferred[name] = types.TypeString(obj.Type(), func(p *types.Package) string { return p.Name() })
			}
		}
		return compilePass(file, options, inferred)
	}
	for i := range result.Files {
		output := &result.Files[i]
		positioned := &Result{Sources: result.Sources, Source: output.Source, Mappings: output.Mappings}
		if err := goSourcePositions(positioned, output.Name); err != nil {
			return nil, e.fail(file, CodeExpr, err.Error())
		}
		output.Source, output.Mappings = positioned.Source, positioned.Mappings
	}
	return result, nil
}

// identifiersIn reports every identifier token of generated Go text.
func identifiersIn(text string) map[string]bool {
	ids := map[string]bool{}
	var sc scanner.Scanner
	fs := token.NewFileSet()
	src := []byte(text)
	sc.Init(fs.AddFile("", -1, len(src)), src, nil, 0)
	for {
		_, tok, lit := sc.Scan()
		if tok == token.EOF {
			return ids
		}
		if tok == token.IDENT {
			ids[lit] = true
		}
	}
}

// libraryImportLines spells the imports of one emitted library file. An
// aliased import whose binding the file's generated text never names is
// dropped: a checked type spelled for the lowering (a call result type, an
// inferred value type) may mint a synthetic binding in a file whose Go output
// keeps the source's untyped form, and gc refuses an unused import. A package
// a type of the file exposes is always a dependency of a package the file
// still imports, so dropping the binding changes no initialization order.
func (e *emitter) libraryImportLines(name string, used map[string]bool) ([]string, string) {
	items := append([]sourceImport(nil), e.fileImports[name]...)
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].path != items[j].path {
			return items[i].path < items[j].path
		}
		return items[i].alias < items[j].alias
	})
	var paths []string
	var out strings.Builder
	seen := map[string]bool{}
	for _, item := range items {
		key := item.alias + "\x00" + item.path
		if seen[key] {
			continue
		}
		if item.aliased && item.alias != "_" && item.alias != "." && used != nil && !used[item.alias] {
			continue
		}
		seen[key] = true
		paths = append(paths, item.path)
		if item.path == "C" && e.sourceFile != nil && len(e.sourceFile.CgoPackages) == 1 {
			out.WriteString(e.sourceFile.CgoPackages[0].Preamble)
		}
		if !item.aliased {
			fmt.Fprintf(&out, "import %s\n", strconv.Quote(item.path))
		} else {
			fmt.Fprintf(&out, "import %s %s\n", item.alias, strconv.Quote(item.path))
		}
	}
	return paths, out.String()
}
