// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:1
//
//line comments-dropped.go:8:1
func F(x int) int {
	// lower:0
//line comments-dropped.go:10:2
	return (x + int(1))
}

// lower:2
//
//line comments-dropped.go:13:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:3
//line comments-dropped.go:8:1
	__bpp0_sourceMain()
}
