// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:6
//
//line decl-reordering.go:5:1
var Fi func(x I) I = F[I]

// lower:7
//
//line decl-reordering.go:11:1
var n int = int(5)

// lower:0
//
//line decl-reordering.go:7:1
type I interface{ M() }

// lower:2
//
//line decl-reordering.go:3:1
func F[T interface{}](x T) T {
	// lower:1
//line decl-reordering.go:3:24
	return (T)(x)
}

// lower:4
//
//line decl-reordering.go:9:1
func G(x interface{}) interface{} {
	// lower:3
//line decl-reordering.go:9:21
	return x
}

// lower:5
//
//line decl-reordering.go:13:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:8
//line decl-reordering.go:7:1
	__bpp0_sourceMain()
}
