// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

import __bpp0_fmt "fmt"
import __bpp0_rt "mvdan.cc/sh/v3/lower/shellrt"
import __bpp0_os "os"

// lower:0
//
//line explicit-deref.go:3:1
type Pair struct{ p1, p2 *int }

// lower:1
//
//line explicit-deref.go:4:1
type Box struct{ pair *Pair }

// lower:4
//
//line explicit-deref.go:6:1
func F(b *Box, p *int, q **int) {
	// lower:2
//line explicit-deref.go:7:2
	(*((*(b)).pair)).p1 = (*((*(b)).pair)).p2
	// lower:3
//line explicit-deref.go:8:2
	(*(p)) = (*(*(q)))
}

// lower:5
//
//line explicit-deref.go:11:1
func __bpp0_sourceMain() {
}
func main() {
	defer func() {
		if v := recover(); v != nil {
			if failure := __bpp0_rt.GuardError(v); failure != nil {
				__bpp0_fmt.Fprintln(__bpp0_os.Stderr, failure)
				__bpp0_os.Exit(failure.ExitStatus())
			}
			panic(v)
		}
	}()
	// lower:6
//line explicit-deref.go:3:1
	__bpp0_sourceMain()
}
