// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

import __bpp0_fmt "fmt"
import __bpp0_rt "mvdan.cc/sh/v3/lower/shellrt"
import __bpp0_os "os"

// lower:0
//
//line guard-prologue.go:3:1
type T struct{ p *int }

// lower:2
//
//line guard-prologue.go:5:1
func F(t *T) int {
	// lower:1
//line guard-prologue.go:6:2
	return (*((*(t)).p))
}

// lower:3
//
//line guard-prologue.go:9:1
func __bpp0_sourceMain() {
}
func main() {
	defer func() {
		if v := recover(); v != nil {
			if failure := __bpp0_rt.GuardError(v); failure != nil {
				__bpp0_fmt.Fprintln(__bpp0_os.Stderr, failure)
				__bpp0_os.Exit(failure.ExitStatus())
			}
			panic(v)
		}
	}()
	// lower:4
//line guard-prologue.go:3:1
	__bpp0_sourceMain()
}
