// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

import __gosource_import_0_0 "strings"

// lower:1
//
//line import-aliasing.go:5:1
func F(s string) bool {
	// lower:0
//line import-aliasing.go:6:2
	return __gosource_import_0_0.HasPrefix(s, string("str"))
}

// lower:2
//
//line import-aliasing.go:9:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:3
//line import-aliasing.go:3:1
	__bpp0_sourceMain()
}
