// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:2
//
//line main-rename.go:3:1
var x int = int(5)

// lower:1
//
//line main-rename.go:6:1
func __bpp0_sourceMain() {
	// lower:0
//line main-rename.go:7:2
	println(x)
}
func main() {
	// lower:3
//line main-rename.go:6:1
	__bpp0_sourceMain()
}
