// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:1
//
//line reparenthesised-exprs.go:3:1
func g(x int) func() {
	// lower:0
//line reparenthesised-exprs.go:3:24
	return func() {
	}
}

// lower:5
//
//line reparenthesised-exprs.go:5:1
func F(a, b, c string, i, n int, s string) int {
	// lower:2
//line reparenthesised-exprs.go:6:2
	(g(i))()
	// lower:3
//line reparenthesised-exprs.go:7:2
	x := (len(([]rune)(s)) + len(([]byte)(((a + b) + c))))
	_ = x
	// lower:4
//line reparenthesised-exprs.go:8:2
	return (((x * i) + n) - (-i))
}

// lower:6
//
//line reparenthesised-exprs.go:11:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:7
//line reparenthesised-exprs.go:3:1
	__bpp0_sourceMain()
}
