// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:5
//
//line sink-statements.go:3:1
func F(n int) []int {
	// lower:0
//line sink-statements.go:4:2
	var r []int
	_ = r
	// lower:1
//line sink-statements.go:5:2
	i := int(0)
	_ = i
	// lower:3
//line sink-statements.go:6:2
	for ; i < n; i++ {
		// lower:2
//line sink-statements.go:7:3
		r = append(r, i)
	}
	// lower:4
//line sink-statements.go:9:2
	return r
}

// lower:6
//
//line sink-statements.go:12:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:7
//line sink-statements.go:3:1
	__bpp0_sourceMain()
}
