// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:0
//
//line synthetic-receiver-names.go:3:1
type M0 struct{ p *int }

// lower:1
//
//line synthetic-receiver-names.go:4:1
type M1 struct{ p *int }

// lower:2
//
//line synthetic-receiver-names.go:6:1
func (__bpp0_unnamed0 M0) M(__bpp0_unnamed1 int, __bpp0_unnamed2 string) {
}

// lower:3
//
//line synthetic-receiver-names.go:8:1
func (__bpp0_unnamed0 *M1) M(__bpp0_unnamed1 int) {
}

// lower:4
//
//line synthetic-receiver-names.go:10:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:5
//line synthetic-receiver-names.go:3:1
	__bpp0_sourceMain()
}
