// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

import __bpp0_fmt "fmt"
import __bpp0_rt "mvdan.cc/sh/v3/lower/shellrt"
import __bpp0_os "os"

// lower:0
//
//line type-assertion.go:3:1
type M interface{ M() }

// lower:1
//
//line type-assertion.go:4:1
type M0 struct{ p *int }

// lower:2
//
//line type-assertion.go:6:1
func (__bpp0_unnamed0 M0) M() {
}

// lower:11
//
//line type-assertion.go:8:1
func F(x M, y interface{}) (M0, bool) {
	// lower:3
//line type-assertion.go:9:2
	v1 := __bpp0_rt.MustValue(__bpp0_rt.Assert[M0](any(x), __bpp0_rt.Assertion{Source: "M", Target: "M0", Impossible: !__bpp0_rt.AssertionPossible[M, M0](), Site: __bpp0_rt.ValueSite{File: "type-assertion.go", Name: "M", Line: 9, Column: 8, Offset: 121}}))
	_ = v1
	// lower:4
//line type-assertion.go:10:2
	var v int
	_ = v
	// lower:5
//line type-assertion.go:11:2
	var ok bool
	_ = ok
	// lower:6
//line type-assertion.go:12:2
	__gosource_tuple_164_0, __gosource_tuple_164_1 := __bpp0_rt.MustAssertOK(__bpp0_rt.AssertOK[int](any(y), __bpp0_rt.Assertion{Source: "interface {}", Target: "int", Impossible: !__bpp0_rt.AssertionPossible[interface{}, int](), Site: __bpp0_rt.ValueSite{File: "type-assertion.go", Name: "interface {}", Line: 12, Column: 14, Offset: 165}}))
	_ = __gosource_tuple_164_0
	_ = __gosource_tuple_164_1
	// lower:7
//line type-assertion.go:12:2
	v = __gosource_tuple_164_0
	// lower:8
//line type-assertion.go:12:5
	(*(&ok)) = __gosource_tuple_164_1
	// lower:9
//line type-assertion.go:13:2
	_ = v
	// lower:10
//line type-assertion.go:14:2
	return v1, ok
}

// lower:12
//
//line type-assertion.go:17:1
func __bpp0_sourceMain() {
}
func main() {
	defer func() {
		if v := recover(); v != nil {
			if failure := __bpp0_rt.GuardError(v); failure != nil {
				__bpp0_fmt.Fprintln(__bpp0_os.Stderr, failure)
				__bpp0_os.Exit(failure.ExitStatus())
			}
			panic(v)
		}
	}()
	// lower:13
//line type-assertion.go:3:1
	__bpp0_sourceMain()
}
