// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.
package main

// lower:5
//
//line untyped-constants.go:3:1
func F(s string, f float64) []byte {
	// lower:0
//line untyped-constants.go:4:2
	i := int(0)
	_ = i
	// lower:2
//line untyped-constants.go:5:2
	if f != float64(0) {
		// lower:1
//line untyped-constants.go:6:3
		i = int(3)
	}
	// lower:3
//line untyped-constants.go:8:2
	println(string("i="), i, float64(1.5))
	// lower:4
//line untyped-constants.go:9:2
	return ([]byte)(string("foo"))[i:]
}

// lower:6
//
//line untyped-constants.go:12:1
func __bpp0_sourceMain() {
}
func main() {
	// lower:7
//line untyped-constants.go:3:1
	__bpp0_sourceMain()
}
